// ReSharper disable All

namespace GigBusiness.Models.CryptoCompare
{
    public class MultipleSymbols
    {
        public Symbol BTC { get; set; }
        public Symbol ETH { get; set; }
        public Symbol XRP { get; set; }
        public Symbol BCH { get; set; }
        public Symbol LTC { get; set; }
        public Symbol BNB { get; set; }
        public Symbol USDT { get; set; }
        public Symbol EOS { get; set; }
        public Symbol BSV { get; set; }
        public Symbol XMR { get; set; }
        public Symbol XLM { get; set; }
        public Symbol TRX { get; set; }
        public Symbol ADA { get; set; }
        public Symbol LEO { get; set; }
        public Symbol DASH { get; set; }
        public Symbol XTZ { get; set; }
        public Symbol LINK { get; set; }
        public Symbol NEO { get; set; }
        public Symbol MIOTA { get; set; }
        public Symbol ATOM { get; set; }
        public Symbol ETC { get; set; }
        public Symbol XEM { get; set; }
        public Symbol MKR { get; set; }
        public Symbol ONT { get; set; }
        public Symbol ZEC { get; set; }
        public Symbol CRO { get; set; }
        public Symbol USDC { get; set; }
        public Symbol VSYS { get; set; }
        public Symbol DOGE { get; set; }
        public Symbol DCR { get; set; }
        public Symbol BTG { get; set; }
        public Symbol VET { get; set; }
        public Symbol QTUM { get; set; }
        public Symbol BAT { get; set; }
        public Symbol HEDG { get; set; }
        public Symbol HT { get; set; }
        public Symbol OMG { get; set; }
        public Symbol EGT { get; set; }
        public Symbol PAX { get; set; }
        public Symbol TUSD { get; set; }
        public Symbol LSK { get; set; }
        public Symbol BTT { get; set; }
        public Symbol KCS { get; set; }
        public Symbol RVN { get; set; }
        public Symbol NANO { get; set; }
        public Symbol BCD { get; set; }
        public Symbol NRG { get; set; }
        public Symbol WAVES { get; set; }
        public Symbol HOT { get; set; }
        public Symbol NPXS { get; set; }
        public Symbol MONA { get; set; }
        public Symbol LAMB { get; set; }
        public Symbol REP { get; set; }
        public Symbol BTS { get; set; }
        public Symbol DGB { get; set; }
        public Symbol EKT { get; set; }
        public Symbol ZRX { get; set; }
        public Symbol AOA { get; set; }
        public Symbol QNT { get; set; }
        public Symbol ICX { get; set; }
        public Symbol IOST { get; set; }
        public Symbol GXC { get; set; }
        public Symbol NEX { get; set; }
        public Symbol BTM { get; set; }
        public Symbol BCN { get; set; }
        public Symbol SC { get; set; }
        public Symbol THETA { get; set; }
        public Symbol INB { get; set; }
        public Symbol KMD { get; set; }
        public Symbol XIN { get; set; }
        public Symbol ABBC { get; set; }
        public Symbol HC { get; set; }
        public Symbol REN { get; set; }
        public Symbol XVG { get; set; }
        public Symbol MAID { get; set; }
        public Symbol ZIL { get; set; }
        public Symbol AE { get; set; }
        public Symbol UUU { get; set; }
        public Symbol DAI { get; set; }
        public Symbol STEEM { get; set; }
        public Symbol VEST { get; set; }
        public Symbol JCT { get; set; }
        public Symbol SNT { get; set; }
        public Symbol WTC { get; set; }
        public Symbol XZC { get; set; }
        public Symbol NET { get; set; }
        public Symbol RIF { get; set; }
        public Symbol ARDR { get; set; }
        public Symbol MCO { get; set; }
        public Symbol ETP { get; set; }
        public Symbol XMX { get; set; }
        public Symbol ENJ { get; set; }
        public Symbol WAX { get; set; }
        public Symbol GNT { get; set; }
        public Symbol MXM { get; set; }
        public Symbol GRIN { get; set; }
        public Symbol ELF { get; set; }
        public Symbol CCCX { get; set; }
        public Symbol ELA { get; set; }
        public Symbol NEXO { get; set; }
        public Symbol HBAR { get; set; }
        public Symbol APPC { get; set; }
        public Symbol DOT { get; set; }
    }
}